steps:
  - name: Checkout code
    uses: [actions/checkout@v4](https://github.com)
  - name: Copy file to destination
    run: cp Source/Test.txt /to/destination/
  - name: Commit and push changes
    run: |
      git config user.name "ramesh24"
      git config user.email "action@github.com"
      git add .
      git commit -m "Automated file copy"
      git push
